name: Integración Continua (CI)
# Definimos el evento que disparará este workflow.
# Se ejecutará con cada 'push' a la rama 'main'.
on:
  push:
    branches: [ main ]
jobs:
  test-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje
        run: echo "El trigger de CI se ejecutó correctamente"
